### PR TITLE
refine approach for config update

### PR DESCRIPTION
**Pull request by mamcderm-usgs**

### CODE REVIEW

**Comment by mamcderm-usgs** [comment]
@isuftin - Not sure if this is the best approach to handle the situation with awslogs.conf existing on the first run and trying to prevent redundant restarts for the agent.

**Comment by isuftin** [comment]
@mamcderm-usgs I think this should work as expected.

**Comment by mamcderm-usgs** [comment]
@isuftin - I was going to tag this with v0.0.2, but looking at previous tags, I'm not sure if that's correct?

**Comment by isuftin** [comment]
@mamcderm-usgs No ability to tag on a branch, unfortunately.

**Pull request merged**
