### PR TITLE
Fixinstallrecipe

### PR DESCRIPTION
**Pull request by mamcderm-usgs**

### CODE REVIEW

**Comment by mamcderm-usgs** [comment]
@isuftin - Would you double check this change to make sure it is correct and that I've submitted the PR properly.  I have not uploaded this version to Chef Server yet.

**Comment by isuftin** [comment]
@mamcderm-usgs One suggestion here. Everything looks good. However, looking at this, it seems like you will have two restarts of the cwlogs service every time an attribute is updated. 

Here's my suggestion: In this resource: https://github.com/mamcderm-usgs/chef-cwlogs/blob/29d172ceea4475c6ce5ac3bfcb8dc0e15fce84e1/recipes/installer.rb#L16-L25

Add a guard that's the opposite of https://github.com/mamcderm-usgs/chef-cwlogs/blob/29d172ceea4475c6ce5ac3bfcb8dc0e15fce84e1/recipes/installer.rb#L35

Essentially, a not_if guard for that same file. 

So when the recipe first runs on the system, it will write out that temp file for the awslogs install service to use to create a config file.

However, once that's written, if you change an attribute on the Chef server, that template will get rewritten to `/tmp/cwlogs.cfg` and it will restart the awslogs service. Then when the next resource also writes out the template to `/var/awslogs/etc/awslogs.conf`, it too will restart the service.

Does what I'm suggesting make sense to you?

**Comment by mamcderm-usgs** [comment]
@isuftin - I understand the change you're suggesting, but with the "opposite guard", you're saying "However, once that's written, if you change an attribute on the Chef server, that template will get rewritten to /tmp/cwlogs.cfg and it will restart the awslogs service. "
It seems like the guard would prevent that from happening...but that should be ok.

**Comment by isuftin** [comment]
Yeah so I'm suggesting the guard to prevent it from happening. The code looks about right. I'll go ahead and merge and tag this

**Pull request merged**
